Выполнил разметку страниц в файлах index.html и catalog.html
htmlacademy-htmlcss/2317829-device-36 pull request #2
Opened 2023-01-26 12:53 UTC by P3L3M3N

2023-01-26 16:57 UTC, vindimm requested changes
Очень хорошее начало, молодец.
Обрати внимание `shift + alt + F` в редакторе автоматически форматирует код. Иногда это помогает выровнять отступы.
Критерий ALLY-01 говорит, что все подписи для доступности должны иметь точку в конце.

2023-01-26 16:57 UTC, vindimm commented on catalog.html
> +              </button>
Внутри `button` можно обойтись без `span`

2023-01-26 16:57 UTC, vindimm commented on catalog.html
> +          </li>
`span` и `img` здесь не нужны. Просто ссылка. Картинку лучше сделать позже псевдоэлементом

2023-01-26 16:57 UTC, vindimm commented on catalog.html
> +          </li>
Лучше сделать ссылку "Корзина", так как это переход на новую страницу. И перед ссылкой сделать спан в котором будет кол-во товаров отображаться.

2023-01-26 16:57 UTC, vindimm commented on catalog.html
> +            <ul class="submenu">
Кажется тега `</li>` не хватает

2023-01-26 16:57 UTC, vindimm commented on catalog.html
> +            </label>
Лучше писать все в одном стиле и везде явно закрывать теги. Это касается `input` , `li` и т.д.

2023-01-26 16:57 UTC, vindimm commented on catalog.html
> +            <option value="expensive">По убыванию цены</option>
У нас есть кнопки для сортировки "вверх" и "вниз". Поэтому достаточно опций "По умолчанию", "По популярности" и "По цене".

2023-01-26 16:57 UTC, vindimm commented on catalog.html
> +            <button class="sorting-button" type="button">&#8595;</button>
Этим кнопкам нужно описание для доступности

2023-01-26 16:57 UTC, vindimm commented on catalog.html
> +        <nav class="product-card-pagination">
Делать пагинацию тегом `nav` не принято. Просто `div` будет достаточно

2023-01-26 16:57 UTC, vindimm commented on catalog.html
> +              </a>
В этих ссылках можно обойтись без `span`

2023-01-26 16:57 UTC, vindimm commented on catalog.html
> +            </li>
Многоточие обычно не является ссылкой. Можно сделать просто `span` или убрать `href`

2023-01-26 16:57 UTC, vindimm commented on catalog.html
> +            </a>
Лучше поправить форматирование, чтобы `</a>` не висел на новой строке

2023-01-26 16:57 UTC, vindimm commented on index.html
> +              </div>
блок управления слайдером нужно вынести отдельно, чтобы он не находился внутри какого-то элемента слайдера

2023-01-26 16:57 UTC, vindimm commented on index.html
> +            </li>
Табы (кнопки выбора нужного элемента) надо вынести в отдельный `div`. Этот `div` будет виден всегда, а вот два из трех блока с информацией будут скрыты.

2023-01-26 16:57 UTC, vindimm commented on index.html
> +        </address>
Пропущен текст "Интернет-магазин Девайс"

2023-01-26 16:57 UTC, vindimm commented on index.html
> +        </form>
"Ваш e-mail" это плейсхолдер. `label` можно оставить для доступности, но его тогда нужно скрыть. `span` внутри кнопки не нужен, так как у кнопки есть текст.

2023-01-28 13:49 UTC, P3L3M3N commented on catalog.html
> +            </label>
А разве тег `input` необходимо закрывать?

2023-01-28 16:27 UTC, P3L3M3N commented on catalog.html
> +            <button class="sorting-button" type="button">&#8595;</button>
Добавил теги `img` с атрибутом `alt="Вверх"`  в `button`.  Для реализации иконок (стрелок)

2023-01-28 16:34 UTC, vindimm commented on catalog.html
> +            </label>
Хорошее замечание. Это я ошибочно написал. Здесь все нормально в разметке.

2023-01-28 17:56 UTC, P3L3M3N commented on index.html
> +        </address>
Не нашел текст "Интернет-магазин Девайс" на макете

2023-01-29 04:16 UTC, vindimm commented on index.html
> +        </address>
<https://disk.yandex.ru/i/0y1hrRqVFODy7Q>

2023-01-29 04:21 UTC, merged

2023-01-29 04:48 UTC, P3L3M3N commented on index.html
> +        </address>
Похоже я случайно удалил этот абзац в копии макета. Исправил.